Create file: *.github/workflows/ci.yml*
---------------------------------------
name: CI - Integration Testing with Database

on:
  push:
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node: [18, 20]

    env:
      MONGO_URI: mongodb://localhost:27017/pft_ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run database migrations
        run: npm run migrate

      - name: Run integration tests
        run: npm run test:integration